data_path: data/exp_data/cv_data_multishot
underground_data_path: data/exp_data/upperDepth_lonlat_400.pt
mask_path: data/exp_data/sea_400.png 
result_base_dir: data/result

model_module: models.multimlpmixer
model_class: Network

device: 1

seed: 42
batch_size: 4
num_epochs: 300
patience: 10
learning_rate: 0.002
cross_validation_folds: 10

img_size_in: [720, 896]
img_size_out: [400, 400]
patch_size: [16, 16]
underground_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12]
output_channels: [0,1,2,3]
in_chans: 6

embed_dim: 64
tokens_mlp_dim: 256
channels_mlp_dim: 1024
num_blocks: 8
f_hidden: 4
drop_rate: 0.1

fno_blocks: 8
fno_softshrink: 0.3

depth: 4
num_heads: 4
mlp_ratio: 4
gpsa_interval: [1, 3]
use_pos_embed: True

img_size_train: [400, 400]
modes_x: 100
modes_y: 100
n_layers: 16
factor: 1
share_weight: false
ff_weight_norm: true
n_ff_layers: 2
layer_norm: false